nacos:
  discovery:
    server-addr: 192.168.122.22:8848
    username: nacos
    password: nacos
    auto-register: true
    register:
      enabled: true
      service-name: nacos-producer-service
      group-name: DEFAULT_GROUP
  config:
    server-addr: 192.168.122.22:8848
    username: nacos
    password: nacos
    namespace: 24373c8c-3894-419b-83eb-b6b9433a9721
    data-id: nacos-producer-dev.yaml
    auto-refresh: true
    group: TEST_GROUP
    type: yaml
    bootstrap:
      enable: true
      log-enable: true